FROM node:18 AS build
WORKDIR /app
COPY package*.json ./
RUN npm install
RUN npm install -g @angular/cli
COPY . .
RUN ng build --configuration=docker --output-path=dist/onlinestoreclient

FROM nginx:latest
COPY --from=build /app/dist/onlinestoreclient /usr/share/nginx/html
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
